[package]
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"
name = "forest_gen"
version = "0.3.1-a"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.1"
lindenmayer = {path = "../lindenmayer"}
