[package]
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"
name = "forest_gen"
version = "0.4.1-b"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.3"
lindenmayer = {path = "../lindenmayer"}
